apiVersion: v1
kind: ClusterRole
metadata:
  name: letsencrypt
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
